description: >
  This command notifies a slack channel of a deployment success

deployment_success_slack_template: &deployment_success_slack_template |
    {
      "text": "'${CIRCLE_JOB}' deployed!",
      "blocks": [
        {
          "type": "header",
          "text": {
            "type": "plain_text",
            "text": "'${CIRCLE_JOB}' deployed! :tada:",
            "emoji": true
          }
        },
        {
          "type": "section",
          "fields": [
            {
              "type": "mrkdwn",
              "text": "*Project*:$CIRCLE_PROJECT_REPONAME"
            },
            {
              "type": "mrkdwn",
              "text": "*When*:$(date +'%m/%d/%Y %T')"
            },
            {
              "type": "mrkdwn",
              "text": "*Environment*:<<parameters.environment>>"
            },
            {
              "type": "mrkdwn",
              "text": "*User*:$CIRCLE_USERNAME"
            }
          ],
          "accessory": {
            "type": "image",
            "image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
            "alt_text": "CircleCI logo"
          }
        },
        {
          "type": "actions",
          "elements": [
            {
              "type": "button",
              "text": {
                "type": "plain_text",
                "text": "View Job"
              },
              "url": "${CIRCLE_BUILD_URL}"
            }
          ]
        }
      ]
    }

# What will this command do?
# Descriptions should be short, simple, and clear.
parameters:
  channel:
    type: string
    default: "#lighthouse-deploy"
    description: "Channel to notify"
  environment:
      default: production
      description: Name of the environment where deployed to.
      type: string    
steps:
  - slack/notify:
      channel: "#lighthouse-deploy"      
      event: pass
      custom: *deployment_success_slack_template  

